using Orchard.ContentManagement.Handlers;
using Orchard.Data;
using Orchard.ContentManagement;
using Orchard.Localization;
using Hazza.Routes.Models;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

// This code was generated by Orchardizer

namespace Hazza.Routes.Handlers {
    public class RedirectRoutesPartHandler : ContentHandler {
        public RedirectRoutesPartHandler() {
            T = NullLocalizer.Instance;

            OnActivated(new Action<ActivatedContentContext, RedirectRoutesPart>(SetupLazyFields));
        }

        public Localizer T { get; set; }
        
        private void SetupLazyFields(ActivatedContentContext context, RedirectRoutesPart part) {
            part._redirectRoutes.Loader(() => JsonConvert.DeserializeObject<List<RedirectRoute>>(part.RoutesString ?? "") ?? new List<RedirectRoute>());
            part._redirectRoutes.Setter(delegate(IEnumerable<RedirectRoute> routes) {
                if (routes == null)
                    routes = new List<RedirectRoute>();

                part.RoutesString = JsonConvert.SerializeObject(routes, Formatting.None);
                return routes;
            });

        }
    }
}